### ISSUE TITLE
Feature: Limit by teams assigned to project

### ISSUE THREAD

**Issue by alekseikorsun** [pavelpower/jira-helper#1]
I have many teams working on projects. Some full-time, some half-time, some - just a bit.
Let's suppose if Project 1 is worked on by Red(R) Team  full-time, Yellow(Y) Team  - half-time and Green(G) Team - just a bit we describe it as:
Pr1 = R3, Y2, G1
Project 2 is worked on by Red Team half-time and Yellow Team half-time. We describe it as:
Pr2 = R2, Y2
Project 3: 
Pr3 = R1, Y1
Project 4:
Pr4 = G2

I would like to set limits for Red Team = 4
For Yellow Team = 4
For Green Team = 3

And so if I take Pr1 and Pr2 - system should show that there is over limit for Red Team.
But if I take Pr1, Pr3, Pr4 - everything is ok.

Example:
![image2023-7-27_14-57-9](https://github.com/pavelpower/jira-helper/assets/113115075/c5cda1bd-9782-422a-ac9d-e6a4ff1c9490)

May be it should be done on this screen: "Edit WIP Limits by field"

**Comment by pavelpower** [comment]
Можно добавить условие для ограничений "Edit WIP Limits by field"
Задать так, в установке лимитов указать специальный символ в значение `≈` - будет означать особый режим
Например, указываем, что в значениях полей будут команда: `≈Team1`, которые надо учесть.
И для нее ограничение на это пересечение свимлайна и колонки будет "2".

Так задать несколько ограничений

А в карточках указывать в каком-то поле значения `Team1[2]|Team2[1]|Team3[1]` 

— Team1[2] — означает, что в этой карточке есть "2" единиц для "Team1"
— Team 2[1] — означает, что в этой карточке есть "1" единица для "Team2"
— Team3[1] — означает, что в этой карточке есть "1" единица для "Team3"

По всему пересечению колонок и свимлайнов считаем количество накопленных едениц, для определенной "Team"
и сравниваем, не превышает ли установленный объем в значении "WIP Limit" для "Team1"

Точно так же можно установить ограничения и для "Team2", "Team3"

**Comment by pavelpower** [comment]
Решил все таки не много по другому

Вот пример как можно настроить так, чтобы считать сумму всех вхождений значений, не зависимо от количества задач

Нужно указать символ `∑` в начале fieldValue, и сразу после него значение поля
Если не указывать этот символ суммы, тогда будет считаться количество задач у которых есть такое значение, не важно сколько таких значений у задачи

<img width="802" alt="Screenshot 2023-09-09 at 20 05 27" src="https://github.com/pavelpower/jira-helper/assets/301646/051663ea-4b02-4974-86ca-4fda272b5c51">

**Comment by pavelpower** [comment]
Обновил условие, теперь в карточках можно значения указать с количеством, пример

* `Team1^2` - значит что в этой карточке 2-а раза по `Team1`
* `Team1, Team1` - так же 20а раза по Team1

Такой подсчет будет работать только в случае настройки fieldValue со значком `∑`

В противном случае будет считать сколько карточек имеет значение указанное в fieldValue
